// Generated by CoffeeScript 2.3.2
(function() {
  var app, db, koa, parser, r, router, url;

  koa = require('koa');

  router = require('koa-router');

  parser = require('koa-body');

  app = new koa();

  r = new router();

  db = {};

  url = 'mongodb://localhost:27017/mock';

  r.get('/', function(ctx) {
    return ctx.body = "<html> <head> <title>HTML Forms are Cool!</title> </head> <body> <form action=\"/subscribe\" method=\"post\"> <input type=\"text\" name=\"email\" placeholder=\"Email Address\"> <input type=\"submit\"> </form> <a href=\"/subscribers\" class=\"button\">list subscribers</a> </body> </html>";
  });

  r.post('/subscribe', parser(), async function(ctx) {
    var email;
    email = ctx.request.body.email;
    if (!email) {
      ctx.status = 400;
      return ctx.body = "missing email";
    } else {
      await db.collection('subs').insert({
        email: email
      });
      return ctx.body = "success";
    }
  });

  r.get('/subscribers', async function(ctx) {
    await db.collection('subs').find().project({
      _id: 0,
      email: 1
    }).toArray(function(err, docs) {
      console.log(docs);
      return ctx.body = docs.map(function(d) {
        return d.email;
      });
    });
  });

  app.use(r.routes());

  require('mongo-mock').MongoClient.connect(url, {}, function(err, _db) {
    db = _db;
    return app.listen(5000, function(e) {
      return console.log("listening on 5000");
    });
  });

}).call(this);
